import crypto from 'crypto';

const generateNonce = () => {
  return crypto.randomBytes(16).toString('base64');
};

export default function Head() {
  const nonce = generateNonce()
  let contentSecurityPolicy = ''
  contentSecurityPolicy = `default-src 'self'; style-src 'nonce-${nonce}';`
  return (
    <>
      <title>Create Next App 1CSP</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      {/* <meta property="Content-Security-Policy" content={contentSecurityPolicy} />
      <meta property="csp-nonce" content={nonce} /> */}

      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
